spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

   #模板引擎
  thymeleaf:
    cache:true
    prefix:classpath:/templates/
    mode:HTML5